penny = 1
nickel = 5
dime = 10
quarter = 25
loonie = 100
toonie = 200
p = 0
n = 0
d = 0
q = 0
l = 0
t = 0
cents = input("The amount of money in cents: ")
cents = int(cents)
if cents >=200:
    t = cents%toonie
    t = str(t)
if cents >=100:
    l = cents%loonie
    l = str(l)
if cents >=25:
    q = cents%quarter
    q = str(q)
if cents >=10:
    d = cents%dime
    d = str(d)
if cents >=5:
    n = cents%nickel
    n =str(n)
if cents >=1:
    p = cents%penny
    p = str(p)
    print("The change is " + t + " toonie(s), " + l + " loonie(s), " + q + " quarter(s), " + d + " dime(s), " + n + "nickels, and " + p + "penny(s).")